version: "3.7"

services:
  mc:
    image: itzg/minecraft-server:${TAG:-java8}
    ports:
    # expose the Minecraft server port outside of container
    - 25565:25565
    env_file:
    - mc-variables.env
    environment:
      LEVEL: ${WORLD_NAME:-world}
      ENFORCE_WHITELIST: "true"
      EULA: "true"
      OVERRIDE_SERVER_PROPERTIES: "true"
      TZ: "Europe/Brussels"
    restart: always
    volumes:
    # use a named, managed volume for data volume
    - data:/data
  backups:
    image: itzg/mc-backup
    environment:
      BACKUP_METHOD: "tar"
      LINK_LATEST: "true"
      EXCLUDES: "*.jar,*.log,cache,logs"
      BACKUP_NAME: ${WORLD_NAME:-world}
      INITIAL_DELAY: ${DELAY:-5m}
      BACKUP_INTERVAL: ${INTERVAL:-1h}
      # instead of network_mode below, could declare RCON_HOST
      RCON_HOST: mc
      TZ: "Europe/Brussels"
    volumes:
    # mount the same volume used by server, but read-only
    - data:/data:ro
    # use a host attached directory so that it in turn can be backed up
    # to external/cloud storage
    - ./mc-backups:/backups
    # share network namespace with server to simplify rcon access
    # network_mode: "service:mc"

volumes:
  data: {}
